-- 2FA Support
-- 2026-01-07

ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_secret VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_recovery_codes TEXT[];
