openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: CUBA ERP 认证服务 API
servers:
  - url: http://localhost:50051
    description: 本地开发环境
paths:
  /register:
    post:
      summary: 用户注册
      description: 注册新用户账号
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - tenant_id
              properties:
                username:
                  type: string
                  description: 用户名
                email:
                  type: string
                  format: email
                  description: 邮箱地址
                password:
                  type: string
                  format: password
                  description: 密码
                tenant_id:
                  type: string
                  description: 租户ID
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  username:
                    type: string
                  status:
                    type: string
  /login:
    post:
      summary: 用户登录
      description: 用户登录并获取访问令牌
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - tenant_id
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
                tenant_id:
                  type: string
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
                  token_type:
                    type: string
                  session_id:
                    type: string
