openapi: 3.0.3
info:
  title: Auth Service API
  description: |
    CUBA ERP 认证服务 API

    提供用户注册、登录、令牌管理、双因素认证等功能。

    ## 认证方式
    大部分接口需要在请求头中携带 JWT Token：
    ```
    Authorization: Bearer <access_token>
    ```

    ## gRPC 服务
    - 服务名: `iam.auth.v1.AuthService`
    - 端口: 50051
  version: 1.0.0
  contact:
    name: CUBA Enterprise Team
    email: dev@cuba.local

servers:
  - url: http://localhost:8080
    description: 本地开发环境 (API Gateway)

tags:
  - name: 认证
    description: 用户认证相关接口
  - name: 用户管理
    description: 用户信息管理接口
  - name: 会话管理
    description: 用户会话管理接口
  - name: 双因素认证
    description: 2FA 相关接口
  - name: 管理员
    description: 管理员专用接口

paths:
  /api/v1/auth/register:
    post:
      tags: [认证]
      summary: 用户注册
      description: 注册新用户账号
      operationId: Register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              username: "john_doe"
              email: "john@example.com"
              password: "SecurePass123!"
              tenant_id: "default"
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: 参数错误
        '409':
          description: 用户名或邮箱已存在

  /api/v1/auth/login:
    post:
      tags: [认证]
      summary: 用户登录
      description: 用户登录并获取访问令牌
      operationId: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              username: "john_doe"
              password: "SecurePass123!"
              tenant_id: "default"
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误

  /api/v1/auth/refresh-token:
    post:
      tags: [认证]
      summary: 刷新令牌
      description: 使用刷新令牌获取新的访问令牌
      operationId: RefreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: 刷新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
        '401':
          description: 刷新令牌无效或已过期

  /api/v1/auth/logout:
    post:
      tags: [会话管理]
      summary: 用户登出
      description: 注销当前会话
      operationId: Logout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '200':
          description: 登出成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'

  /api/v1/auth/current-user:
    post:
      tags: [用户管理]
      summary: 获取当前用户信息
      description: 获取当前登录用户的详细信息
      operationId: GetCurrentUser
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCurrentUserResponse'

  /api/v1/auth/change-password:
    post:
      tags: [用户管理]
      summary: 修改密码
      description: 修改当前用户密码
      operationId: ChangePassword
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: 修改成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePasswordResponse'

  /api/v1/auth/update-profile:
    post:
      tags: [用户管理]
      summary: 更新个人资料
      description: 更新用户个人资料信息
      operationId: UpdateProfile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProfileResponse'

  /api/v1/auth/2fa/enable:
    post:
      tags: [双因素认证]
      summary: 启用双因素认证
      description: 为当前用户启用 2FA，返回 TOTP 密钥和二维码
      operationId: Enable2FA
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enable2FAResponse'

  /api/v1/auth/2fa/verify:
    post:
      tags: [双因素认证]
      summary: 验证双因素认证
      description: 验证 2FA 代码（绑定阶段）
      operationId: Verify2FA
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Verify2FARequest'
      responses:
        '200':
          description: 验证成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verify2FAResponse'

  /api/v1/auth/2fa/verify-code:
    post:
      tags: [双因素认证]
      summary: 登录时验证 2FA
      description: 登录流程中验证 2FA 代码
      operationId: Verify2FACode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Verify2FACodeRequest'
      responses:
        '200':
          description: 验证成功，返回登录令牌
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /api/v1/auth/perm-codes:
    post:
      tags: [用户管理]
      summary: 获取权限码
      description: 获取当前用户的所有权限码（用于前端权限控制）
      operationId: GetPermCodes
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPermCodesResponse'

  /api/v1/auth/users:
    post:
      tags: [管理员]
      summary: 列出用户
      description: 列出所有用户（需要管理员权限）
      operationId: ListUsers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListUsersRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'

  /api/v1/auth/admin/update-user:
    post:
      tags: [管理员]
      summary: 管理员更新用户
      description: 管理员更新用户信息
      operationId: AdminUpdateUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminUpdateUserRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminUpdateUserResponse'

  /api/v1/auth/admin/delete-user:
    post:
      tags: [管理员]
      summary: 删除用户
      description: 删除指定用户
      operationId: DeleteUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteUserRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUserResponse'

  /api/v1/auth/sessions:
    post:
      tags: [会话管理]
      summary: 列出用户会话
      description: 获取用户的所有活跃会话
      operationId: ListUserSessions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListUserSessionsRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUserSessionsResponse'

  /api/v1/auth/sessions/revoke:
    post:
      tags: [会话管理]
      summary: 撤销会话
      description: 撤销指定会话
      operationId: RevokeSession
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeSessionRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevokeSessionResponse'

  /api/v1/auth/validate-token:
    post:
      tags: [认证]
      summary: 验证令牌
      description: 验证令牌是否有效（内部调用）
      operationId: ValidateToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateTokenRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateTokenResponse'

  /api/v1/auth/audit-logs:
    post:
      tags: [管理员]
      summary: 获取审计日志
      description: 获取用户操作审计日志
      operationId: GetAuditLogs
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAuditLogsRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuditLogsResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT 访问令牌

  schemas:
    RegisterRequest:
      type: object
      required:
        - username
        - password
        - email
        - tenant_id
      properties:
        username:
          type: string
          description: 用户名（唯一）
          minLength: 3
          maxLength: 100
        password:
          type: string
          format: password
          description: 密码（最少8位）
          minLength: 8
        email:
          type: string
          format: email
          description: 邮箱地址（唯一）
        tenant_id:
          type: string
          description: 租户ID
        idempotency_key:
          type: string
          description: 幂等性键（可选）

    RegisterResponse:
      type: object
      properties:
        user_id:
          type: string
          description: 用户ID
        username:
          type: string
          description: 用户名
        status:
          type: string
          enum: [ACTIVE, PENDING, SUSPENDED]
          description: 用户状态

    LoginRequest:
      type: object
      required:
        - username
        - password
        - tenant_id
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          format: password
          description: 密码
        tenant_id:
          type: string
          description: 租户ID
        two_factor_code:
          type: string
          description: 2FA 验证码（启用2FA时必填）

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT 访问令牌
        refresh_token:
          type: string
          description: 刷新令牌
        expires_in:
          type: integer
          description: 过期时间（秒）
        token_type:
          type: string
          description: 令牌类型
          example: "Bearer"
        session_id:
          type: string
          description: 会话ID

    RefreshTokenRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          description: 刷新令牌

    RefreshTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: 新的访问令牌
        refresh_token:
          type: string
          description: 新的刷新令牌
        expires_in:
          type: integer
          description: 过期时间（秒）

    LogoutRequest:
      type: object
      properties:
        session_id:
          type: string
          description: 会话ID（可选，默认当前会话）

    LogoutResponse:
      type: object
      properties:
        success:
          type: boolean
          description: 是否成功
        message:
          type: string
          description: 消息

    GetCurrentUserResponse:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        email:
          type: string
        tenant_id:
          type: string
        roles:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ChangePasswordRequest:
      type: object
      required:
        - old_password
        - new_password
      properties:
        old_password:
          type: string
          format: password
        new_password:
          type: string
          format: password

    ChangePasswordResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    UpdateProfileRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        display_name:
          type: string
        avatar_url:
          type: string
          format: uri

    UpdateProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    Enable2FAResponse:
      type: object
      properties:
        secret:
          type: string
          description: TOTP 密钥
        qr_code_url:
          type: string
          description: 二维码 URL
        backup_codes:
          type: array
          items:
            type: string
          description: 备份码列表

    Verify2FARequest:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: 2FA 验证码

    Verify2FAResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    Verify2FACodeRequest:
      type: object
      required:
        - user_id
        - code
      properties:
        user_id:
          type: string
        code:
          type: string

    GetPermCodesResponse:
      type: object
      properties:
        perm_codes:
          type: array
          items:
            type: string
          description: 权限码列表

    ListUsersRequest:
      type: object
      properties:
        page:
          type: integer
          default: 1
        page_size:
          type: integer
          default: 20
        tenant_id:
          type: string
        status:
          type: string

    ListUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        total_count:
          type: integer
        page:
          type: integer
        page_size:
          type: integer

    User:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        email:
          type: string
        status:
          type: string
        tenant_id:
          type: string
        created_at:
          type: string
          format: date-time

    AdminUpdateUserRequest:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
        email:
          type: string
        status:
          type: string
        roles:
          type: array
          items:
            type: string

    AdminUpdateUserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    DeleteUserRequest:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string

    DeleteUserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ListUserSessionsRequest:
      type: object
      properties:
        user_id:
          type: string

    ListUserSessionsResponse:
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/UserSession'

    UserSession:
      type: object
      properties:
        session_id:
          type: string
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        ip_address:
          type: string
        user_agent:
          type: string

    RevokeSessionRequest:
      type: object
      required:
        - session_id
      properties:
        session_id:
          type: string

    RevokeSessionResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ValidateTokenRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string

    ValidateTokenResponse:
      type: object
      properties:
        valid:
          type: boolean
        user_id:
          type: string
        tenant_id:
          type: string
        roles:
          type: array
          items:
            type: string

    GetAuditLogsRequest:
      type: object
      properties:
        user_id:
          type: string
        action:
          type: string
        from_date:
          type: string
          format: date
        to_date:
          type: string
          format: date
        page:
          type: integer
        page_size:
          type: integer

    GetAuditLogsResponse:
      type: object
      properties:
        logs:
          type: array
          items:
            $ref: '#/components/schemas/AuditLog'
        total_count:
          type: integer

    AuditLog:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        action:
          type: string
        resource:
          type: string
        details:
          type: string
        ip_address:
          type: string
        created_at:
          type: string
          format: date-time
