openapi: 3.0.3
info:
  title: RBAC Service API
  description: |
    CUBA ERP 角色权限管理服务 API

    提供角色创建、权限分配、权限检查等功能。

    ## gRPC 服务
    - 服务名: `iam.rbac.v1.RBACService`
    - 端口: 50052
  version: 1.0.0
  contact:
    name: CUBA Enterprise Team
    email: dev@cuba.local

servers:
  - url: http://localhost:8080
    description: 本地开发环境 (API Gateway)

tags:
  - name: 角色管理
    description: 角色创建、更新、删除
  - name: 权限管理
    description: 权限分配和检查
  - name: 用户角色
    description: 用户角色关联

paths:
  /api/v1/rbac/roles:
    post:
      tags: [角色管理]
      summary: 创建角色
      description: 创建新的角色
      operationId: CreateRole
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoleRequest'
            example:
              name: "finance_manager"
              description: "财务经理角色"
              tenant_id: "default"
              permissions:
                - "gl.journal_entry.create"
                - "gl.journal_entry.post"
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'

  /api/v1/rbac/roles/update:
    post:
      tags: [角色管理]
      summary: 更新角色
      description: 更新角色信息（部分字段）
      operationId: UpdateRole
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoleRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'

  /api/v1/rbac/roles/delete:
    post:
      tags: [角色管理]
      summary: 删除角色
      description: 删除指定角色
      operationId: DeleteRole
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteRoleRequest'
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOperationResult'

  /api/v1/rbac/roles/list:
    post:
      tags: [角色管理]
      summary: 列出角色
      description: 获取角色列表
      operationId: ListRoles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListRolesRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRolesResponse'

  /api/v1/rbac/user-roles/assign:
    post:
      tags: [用户角色]
      summary: 分配角色给用户
      description: 将角色分配给指定用户
      operationId: AssignRoleToUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignRoleToUserRequest'
            example:
              user_id: "user-uuid"
              role_id: "role-uuid"
              tenant_id: "default"
      responses:
        '200':
          description: 分配成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignRoleToUserResponse'

  /api/v1/rbac/user-roles/remove:
    post:
      tags: [用户角色]
      summary: 移除用户角色
      description: 从用户移除指定角色
      operationId: RemoveRoleFromUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveRoleFromUserRequest'
      responses:
        '200':
          description: 移除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveRoleFromUserResponse'

  /api/v1/rbac/user-roles:
    post:
      tags: [用户角色]
      summary: 获取用户角色
      description: 获取指定用户拥有的所有角色
      operationId: GetUserRoles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUserRolesRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserRolesResponse'

  /api/v1/rbac/permissions/check:
    post:
      tags: [权限管理]
      summary: 检查权限
      description: 检查用户是否拥有指定权限
      operationId: CheckPermissions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPermissionsRequest'
            example:
              user_id: "user-uuid"
              permissions:
                - "gl.journal_entry.create"
                - "gl.journal_entry.post"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckPermissionsResponse'
              example:
                results:
                  gl.journal_entry.create: true
                  gl.journal_entry.post: false

  /api/v1/rbac/permissions/grant:
    post:
      tags: [权限管理]
      summary: 赋予角色权限
      description: 给角色赋予指定权限
      operationId: GrantPermissionsToRole
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantPermissionsRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrantPermissionsResponse'

  /api/v1/rbac/permissions:
    post:
      tags: [权限管理]
      summary: 列出所有权限
      description: 列出系统中定义的所有权限
      operationId: ListPermissions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaginationRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPermissionsResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateRoleRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 角色名称
        description:
          type: string
          description: 角色描述
        tenant_id:
          type: string
          description: 租户ID
        permissions:
          type: array
          items:
            type: string
          description: 权限列表

    UpdateRoleRequest:
      type: object
      required:
        - role_id
      properties:
        role_id:
          type: string
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string

    DeleteRoleRequest:
      type: object
      required:
        - role_id
      properties:
        role_id:
          type: string

    ListRolesRequest:
      type: object
      properties:
        tenant_id:
          type: string
        page:
          type: integer
          default: 1
        page_size:
          type: integer
          default: 20

    ListRolesResponse:
      type: object
      properties:
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        total_count:
          type: integer
        page:
          type: integer
        page_size:
          type: integer

    Role:
      type: object
      properties:
        role_id:
          type: string
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string
        tenant_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AssignRoleToUserRequest:
      type: object
      required:
        - user_id
        - role_id
      properties:
        user_id:
          type: string
        role_id:
          type: string
        tenant_id:
          type: string

    AssignRoleToUserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    RemoveRoleFromUserRequest:
      type: object
      required:
        - user_id
        - role_id
      properties:
        user_id:
          type: string
        role_id:
          type: string

    RemoveRoleFromUserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    GetUserRolesRequest:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string

    GetUserRolesResponse:
      type: object
      properties:
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'

    CheckPermissionsRequest:
      type: object
      required:
        - user_id
        - permissions
      properties:
        user_id:
          type: string
        permissions:
          type: array
          items:
            type: string

    CheckPermissionsResponse:
      type: object
      properties:
        results:
          type: object
          additionalProperties:
            type: boolean
          description: 权限检查结果映射

    GrantPermissionsRequest:
      type: object
      required:
        - role_id
        - permissions
      properties:
        role_id:
          type: string
        permissions:
          type: array
          items:
            type: string

    GrantPermissionsResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    PaginationRequest:
      type: object
      properties:
        page:
          type: integer
          default: 1
        page_size:
          type: integer
          default: 20

    ListPermissionsResponse:
      type: object
      properties:
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        total_count:
          type: integer

    Permission:
      type: object
      properties:
        code:
          type: string
          description: 权限码
        name:
          type: string
          description: 权限名称
        description:
          type: string
          description: 权限描述
        module:
          type: string
          description: 所属模块

    BatchOperationResult:
      type: object
      properties:
        success:
          type: boolean
        affected_count:
          type: integer
        message:
          type: string
