openapi: 3.0.0
info:
  title: RBAC Service API
  version: 1.0.0
  description: CUBA ERP 角色权限管理服务 API
servers:
  - url: http://localhost:50052
paths:
  /roles:
    get:
      summary: 列出所有角色
      responses:
        '200':
          description: 成功
