#!/bin/bash
# Automated Service Refactoring Script
# Purpose: Refactor all remaining services to use cuba-service::ServiceBootstrapper
# Author: Generated by Antigravity
# Date: 2026-01-17

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counter for statistics
TOTAL_SERVICES=0
SUCCESSFUL_REFACTORS=0
FAILED_REFACTORS=0
SKIPPED_SERVICES=0

# Log functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to add cuba-service dependency to Cargo.toml
add_cuba_service_dependency() {
    local cargo_toml="$1"
    
    # Check if dependency already exists
    if grep -q "cuba-service" "$cargo_toml"; then
        log_warning "cuba-service dependency already exists in $cargo_toml"
        return 0
    fi
    
    # Add dependency after cuba-telemetry line
    if grep -q "cuba-telemetry" "$cargo_toml"; then
        sed -i '' '/cuba-telemetry.*workspace = true/a\
cuba-service = { path = "../../../libs/cuba-service" }
' "$cargo_toml"
        log_success "Added cuba-service dependency to $cargo_toml"
        return 0
    else
        log_error "Could not find cuba-telemetry in $cargo_toml"
        return 1
    fi
}

# Function to refactor main.rs
refactor_main_rs() {
    local main_rs="$1"
    local service_port="$2"
    local backup="${main_rs}.backup"
    
    # Create backup
    cp "$main_rs" "$backup"
    
    # Check if already refactored
    if grep -q "cuba_service::ServiceBootstrapper" "$main_rs"; then
        log_warning "$main_rs already refactored"
        rm "$backup"
        return 0
    fi
    
    # Create a temporary Python script for the refactoring
    python3 << 'PYTHON_SCRIPT' "$main_rs" "$service_port"
import sys
import re

main_rs_path = sys.argv[1]
service_port = sys.argv[2]

with open(main_rs_path, 'r') as f:
    content = f.read()

# Remove imports
content = re.sub(r'use dotenvy::dotenv;\n?', '', content)
content = re.sub(r'use cuba_database::\{[^}]*\};\n?', '', content)

# Replace initialization block
# Pattern 1: Multi-line format
pattern1 = r'cuba_telemetry::init_telemetry\(\);\s*\n\s*dotenv\(\)\.ok\(\);\s*\n\s*(?://.*\n\s*)*let addr = "[^"]+".parse\(\)\?;\s*\n\s*(?:info!\([^)]+\);\s*\n\s*)?(?://.*\n\s*)*(?:let db_config = DatabaseConfig::default\(\);\s*\n\s*let pool = init_pool\(&db_config\)\.await\?;|let pool = init_pool\(&DatabaseConfig::default\(\)\)\.await\?;)'

replacement1 = f'''// Bootstrap Service
    let context = cuba_service::ServiceBootstrapper::run({service_port}).await?;
    let pool = context.db_pool;
    let addr = context.addr;'''

content = re.sub(pattern1, replacement1, content, flags=re.MULTILINE)

# Pattern 2: Compact format
pattern2 = r'cuba_telemetry::init_telemetry\(\);dotenv\(\)\.ok\(\);.*?let pool = init_pool\(&db_config\)\.await\?;'

content = re.sub(pattern2, replacement1.replace('\n    ', ''), content, flags=re.DOTALL)

with open(main_rs_path, 'w') as f:
    f.write(content)

print("Refactored successfully")
PYTHON_SCRIPT
    
    if [ $? -eq 0 ]; then
        log_success "Refactored $main_rs"
        rm "$backup"
        return 0
    else
        log_error "Failed to refactor $main_rs, restoring backup"
        mv "$backup" "$main_rs"
        return 1
    fi
}

# Function to get service port from main.rs
get_service_port() {
    local main_rs="$1"
    local port=$(grep -E '(let addr|parse\(\)).*:[0-9]+' "$main_rs" | grep -oE '[0-9]{5}' | head -1)
    echo "${port:-50000}"
}

# Function to refactor a single service
refactor_service() {
    local service_path="$1"
    local service_name=$(basename "$service_path")
    
    log_info "Processing $service_name..."
    
    local main_rs="${service_path}/src/main.rs"
    local cargo_toml="${service_path}/Cargo.toml"
    
    # Check if files exist
    if [ ! -f "$main_rs" ]; then
        log_warning "main.rs not found for $service_name, skipping"
        ((SKIPPED_SERVICES++))
        return 0
    fi
    
    if [ ! -f "$cargo_toml" ]; then
        log_warning "Cargo.toml not found for $service_name, skipping"
        ((SKIPPED_SERVICES++))
        return 0
    fi
    
    # Get service port
    local port=$(get_service_port "$main_rs")
    log_info "Detected port: $port for $service_name"
    
    # Step 1: Add dependency
    if ! add_cuba_service_dependency "$cargo_toml"; then
        log_error "Failed to add dependency for $service_name"
        ((FAILED_REFACTORS++))
        return 1
    fi
    
    # Step 2: Refactor main.rs
    if ! refactor_main_rs "$main_rs" "$port"; then
        log_error "Failed to refactor main.rs for $service_name"
        ((FAILED_REFACTORS++))
        return 1
    fi
    
    ((SUCCESSFUL_REFACTORS++))
    log_success "✓ $service_name refactored successfully"
    return 0
}

# Main execution
main() {
    log_info "Starting automated refactoring of remaining services..."
    log_info "Working directory: $(pwd)"
    echo ""
    
    # List of all modules and their services
    declare -a MODULES=("am" "cs" "hr" "mf" "pm" "rd" "sd")
    
    for module in "${MODULES[@]}"; do
        log_info "=== Processing module: $module ==="
        
        # Find all services in the module
        for service_dir in apps/${module}/*-service; do
            if [ -d "$service_dir" ]; then
                ((TOTAL_SERVICES++))
                refactor_service "$service_dir"
                echo ""
            fi
        done
    done
    
    # Print summary
    echo ""
    echo "========================================"
    log_info "Refactoring Summary"
    echo "========================================"
    echo "Total services processed: $TOTAL_SERVICES"
    log_success "Successful refactors: $SUCCESSFUL_REFACTORS"
    log_error "Failed refactors: $FAILED_REFACTORS"
    log_warning "Skipped services: $SKIPPED_SERVICES"
    echo "========================================"
    
    if [ $FAILED_REFACTORS -eq 0 ]; then
        log_success "All services refactored successfully! 🎉"
        echo ""
        log_info "Next step: Run 'cargo build' to verify all services compile"
        return 0
    else
        log_error "Some services failed to refactor. Please review the errors above."
        return 1
    fi
}

# Check if running from project root
if [ ! -d "apps" ] || [ ! -d "libs" ]; then
    log_error "Please run this script from the project root directory"
    exit 1
fi

# Run main function
main
