#!/bin/bash
# Build Verification Script
# Purpose: Build all refactored services and report results
# Author: Generated by Antigravity

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Build all services by module
build_module() {
    local module=$1
    log_info "Building $module module services..."
    
    local services=$(ls apps/${module}/*-service 2>/dev/null | xargs -n1 basename | sed 's/-service//' | tr '\n' ' ')
    
    if [ -z "$services" ]; then
        log_info "No services found in $module module"
        return 0
    fi
    
    # Build all services in the module
    local packages=$(echo $services | sed 's/ / -p /g' | sed 's/^/-p /')
    
    if cargo build $packages 2>&1 | tee /tmp/build_${module}.log | tail -20; then
        log_success "✓ $module module built successfully"
        return 0
    else
        log_error "✗ $module module build failed"
        return 1
    fi
}

main() {
    log_info "Starting build verification for all refactored services..."
    echo ""
    
    declare -a MODULES=("am" "cs" "hr" "mf" "pm" "rd" "sd")
    FAILED_MODULES=0
    
    for module in "${MODULES[@]}"; do
        if ! build_module "$module"; then
            ((FAILED_MODULES++))
        fi
        echo ""
    done
    
    echo "========================================"
    if [ $FAILED_MODULES -eq 0 ]; then
        log_success "All modules built successfully! 🎉"
    else
        log_error "$FAILED_MODULES module(s) failed to build"
    fi
    echo "========================================"
}

cd "$(dirname "$0")/.." || exit 1
main
